import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tổng quan',
      collapsed: false,
      items: [
        'intro',
        'ke-hoach-tong-the',
        'roadmap',
      ],
    },
    {
      type: 'category',
      label: 'Gameplay & Cơ chế',
      collapsed: false,
      items: [
        'chi-tiet-co-che-gameplay',
        'cac-chuc-nang-chinh-va-bo-cuc',
        'chi-tiet-man-hinh-dieu-khien',
        'chi-tiet-man-hinh-chien-dau',
      ],
    },
    {
      type: 'category',
      label: 'Hệ thống Game',
      collapsed: false,
      items: [
        'he-thong-chi-so-va-tang-truong',
        'he-thong-kinh-te-va-tai-nguyen',
        'he-thong-ky-nang',
        'he-thong-trang-bi',
        'he-thong-dong-doi',
        'he-thong-gacha',
      ],
    },
    {
      type: 'category',
      label: 'Thiết kế Assets',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'assets-design-spec',
        },
      ],
    },
  ],
};

export default sidebars;
