import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Tổng quan",
      collapsed: false,
      items: ["intro", "ke-hoach-tong-the"],
    },
    {
      type: "category",
      label: "Kế hoạch và lộ trình",
      items: [
        "plan-timelines/ke-hoach-san-xuat",
        "plan-timelines/quan-ly-du-an",
        "noi-dung-mo-rong",
        "kien-truc-ky-thuat",
      ],
    },
    {
      type: "category",
      label: "Gameplay và cơ chế",
      items: [
        "chi-tiet-co-che-gameplay",
        "cac-chuc-nang-chinh-va-bo-cuc",
        "chi-tiet-man-hinh-dieu-khien",
        "chi-tiet-man-hinh-chien-dau",
        "huong-dan-nguoi-choi-moi",
      ],
    },
    {
      type: "category",
      label: "Hệ thống game",
      items: [
        "he-thong-chi-so-va-tang-truong",
        "he-thong-kinh-te-va-tai-nguyen",
        "he-thong-ky-nang",
        "he-thong-trang-bi",
        "he-thong-dong-doi",
        "he-thong-quai-vat",
        "he-thong-gacha",
        "he-thong-nhiem-vu",
        "he-thong-prestige",
        "he-thong-event",
        "he-thong-pvp-arena",
        "he-thong-guild",
        "he-thong-battle-pass",
        "he-thong-vip",
      ],
    },
    {
      type: "category",
      label: "Tính năng bổ sung",
      items: [
        "systems/collection-system",
        "systems/hub-tab",
        "systems/skill-tree-standalone",
        "ui-boosters/mobile-ui-redesign",
        "ui-boosters/afk-lock-screen",
        "ui-boosters/continue-gacha",
        "ui-boosters/upgradable-point",
        "effects/stage-clear-effect",
        "effects/boss-entrance-effect",
        "effects/point-click-effect",
      ],
    },
    {
      type: "category",
      label: "Cân bằng và Công thức",
      items: [
        "bang-can-bang-kinh-te",
        "he-thong-cong-thuc-toan-hoc/tong-quan",
        "he-thong-cong-thuc-toan-hoc/chien-dau",
        "he-thong-cong-thuc-toan-hoc/tang-truong",
        "he-thong-cong-thuc-toan-hoc/kinh-te",
        "he-thong-cong-thuc-toan-hoc/gacha-xac-suat",
      ],
    },
    {
      type: "category",
      label: "Bảng toán chỉ số",
      items: [
        {
          type: "autogenerated",
          dirName: "bang-toan-chi-so",
        },
      ],
    },
    {
      type: "category",
      label: "Thiết kế assets",
      items: [
        {
          type: "autogenerated",
          dirName: "assets-design-spec",
        },
      ],
    },
  ],
};

export default sidebars;
